<?php
/**
 * Template Name: Privacy Policy
 */
get_header(); ?>

    <section class="page-hero" style="background: linear-gradient(135deg, rgba(0, 0, 0, 0.8) 0%, rgba(0, 0, 0, 0.6) 100%), url('<?php echo get_template_directory_uri(); ?>/assets/Content/Website_Gallery/10XTO_tennis_player_serving_action_shot.jpg'); background-size: cover; background-position: center; height: 30vh; min-height: 250px;">
        <div class="container">
            <h1>Privacy Policy</h1>
        </div>
    </section>

    <section class="legal-content" style="padding: 4rem 0; background-color: #fff;">
        <div class="container" style="max-width: 800px; margin: 0 auto; padding: 0 20px;">
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">This Privacy Policy applies to all users of this 10XTO Athletic Club (“10XTO”) web site (“Site”) and the web sites (“Sites”) of affiliated hotels (“we” or “us”). By using this Site or 10XTO's affiliated sites you are agreeing to comply with and be bound by this Privacy Policy. If you do not agree to this Privacy Policy, you may not access or use the Sites.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">This online privacy policy (this “Privacy Policy”) applies only to information collected through the Sites, including information posted by you on the Sites. It does not apply to information collected through other channels, such as over the phone or in person.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Some of the information we collect through the Sites may be personal information, namely “Identifier Information,” as defined herein, that identifies you personally, alone or in combination with other information available to us. Other information may be non-personally identifiable information, such as information collected by cookies.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Your Consent</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">By using the Sites and opting in to accept the terms of this Privacy Policy, you are consenting to the collection, use, disclosure, and transfer of your information as described in this Privacy Policy (and any Privacy Notices that apply to you). If you do not consent to the collection, use, disclosure and transfer of your information as described in this Privacy Policy (and any Privacy Notices that apply to you), you may not use the Sites. If you have questions about this Privacy Policy, or any Privacy Notice, please contact us using the information provided below.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Your Choices</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">We respect your right to make choices about the ways we collect, use, and disclose your information. This Privacy Policy describes some of your choices, such as your choice to opt in to receiving “Cookies.”</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Cookies are small text files that are created automatically in your browser and are stored on your device (laptop, tablet, smartphone, PC, etc.) when you visit our site. Cookies do not harm your device and do not contain any viruses or other malicious software. Cookies store information about your interaction with our website on your device. However, this does not result in an immediate knowledge of your identity. We mainly use cookies to make our website more user-friendly, effective, safe, and secure.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">We use session Cookies to recognize which webpages you have opened during your visit on our Sites. Cookies also provide certain functionalities.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">In addition, we also use temporary Cookies that are stored on your device for a specific period of time to optimize usability of our Sites and to statistically evaluate the use of our offering. If you return to our Sites to take advantage of our services, the Sites will automatically recognize that you have frequented the Sites before, and which settings you have chosen and entries you have made, so that you do not need to reenter them. You may change previously expressed preferences regarding how we use your information. If, at any time, you wish to be taken off our mailing lists, please contact us using the information provided below.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Personal Information</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">The Sites must collect some information from you (“Identifier Information”) to allow you to use and access services, products and materials. Identifier Information is information relating to an identified or identifiable natural person. An identifiable natural person is one who can be identified, directly or indirectly, by reference to an identifier such as a name, an identification number, location data, or an online identifier.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Types of Information</h3>
            <ul style="margin-bottom: 1.5rem; padding-left: 20px;">
                <li style="margin-bottom: 0.5rem; color: #444;">Identifying information such as your name, addresses, telephone numbers or email addresses when you register for an account with us.</li>
                <li style="margin-bottom: 0.5rem; color: #444;">Financial information (such as credit card or bank account numbers) in connection with a transaction.</li>
                <li style="margin-bottom: 0.5rem; color: #444;">Postage, billing and other information used to purchase an item.</li>
                <li style="margin-bottom: 0.5rem; color: #444;">Additional information we are required or authorized by applicable national laws to collect and process in order to authenticate or identify you, or to verify the information we have collected.</li>
                <li style="margin-bottom: 0.5rem; color: #444;">Computer and connection information such as statistics on your page views, traffic to and from the sites, referral URL, ad data, your IP address, your browsing history, and your web log information.</li>
            </ul>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">What do we use it for?</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Generally, we use the information we collect through the Sites:</p>
            <ul style="margin-bottom: 1.5rem; padding-left: 20px;">
                <li style="margin-bottom: 0.5rem; color: #444;">to provide the information, products and services you request;</li>
                <li style="margin-bottom: 0.5rem; color: #444;">to provide you with effective customer service;</li>
                <li style="margin-bottom: 0.5rem; color: #444;">to provide you with a personalized experience when you use the Sites;</li>
                <li style="margin-bottom: 0.5rem; color: #444;">to contact you with information and notices related to your use of the Sites;</li>
                <li style="margin-bottom: 0.5rem; color: #444;">to contact you with special offers and other information we believe will be of interest to you (in accordance with any privacy preferences you have expressed to us);</li>
                <li style="margin-bottom: 0.5rem; color: #444;">to invite you to participate in surveys and provide feedback to us (in accordance with any privacy preferences you have expressed to us);</li>
                <li style="margin-bottom: 0.5rem; color: #444;">to improve the content, functionality and usability of the Sites;</li>
                <li style="margin-bottom: 0.5rem; color: #444;">to better understand your needs and interests;</li>
                <li style="margin-bottom: 0.5rem; color: #444;">to improve our products and services;</li>
                <li style="margin-bottom: 0.5rem; color: #444;">to improve our marketing and promotional efforts;</li>
                <li style="margin-bottom: 0.5rem; color: #444;">for security, credit or fraud prevention purposes;</li>
                <li style="margin-bottom: 0.5rem; color: #444;">for any other purpose identified in an applicable Privacy Notice, click-through agreement, or other agreement between you and us; and</li>
                <li style="margin-bottom: 0.5rem; color: #444;">for good faith compliance with applicable law, a court order, or a subpoena.</li>
            </ul>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Registration/User account</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">You have the opportunity to register on our Sites. To do so you need to provide personal data. The registration is voluntary. The personal data being transferred depends on the respective input in the form used for the registration. The personal data recorded will be used for the purposes of our offer as well as for contacting you for information regarding registration or contractual communications. A personal access allows you to look at your personal data and to make changes to this data. Your data will be stored until you delete the user account or instruct us to delete your data. Provided that we are obliged to retain your personal data on the basis of statutory retention periods, in particular tax and commercial law, the processing of your personal data will be restricted accordingly until the expiration of the retention periods and then the data will be deleted.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">If you register on our Sites or use the user account, we store the IP address and the time of the respective use. The storage takes place on the basis of our legitimate interest. The storage is also in your interest to protect you from misuse and other unauthorized use. The user account and the data stored in this connection also serve in particular to facilitate the purchase and to allow access to historical orders and the writing of customer reviews. A transfer of this data to third parties does not take place unless it is required to fulfil contractual obligations.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">How long is information retained?</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">We generally retain your information only as long as reasonably necessary to provide you the services available on or through the Sites or to comply with applicable law.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">How is information collected?</p>
            <ul style="margin-bottom: 1.5rem; padding-left: 20px;">
                <li style="margin-bottom: 0.5rem; color: #444;">Information You Manually Provide. The Sites collect the information you manually provide (using your keyboard, mouse, or touchpad) when you use the Sites. For example, we collect the information you provide when you request services, send us questions, or otherwise interact with the Sites. Some of the information you manually provide may be personal information, such as your name and contact information.</li>
                <li style="margin-bottom: 0.5rem; color: #444;">Information from your browser or device. The Site collects information that is sent to us automatically by your web browser or mobile device. This information typically includes your IP address, the name of your operating system, the name and version of your browser, name and URL of the accessed file, the date and time of your visit, Website the referral request comes from (i.e., the referrer URL), and the pages on the Sites that you visit. The information we receive may depend on your browser or device settings. The information we receive from your web browser and device typically is not, in and of itself, personally identifiable. However, we may combine it with other information in an attempt to identify you or we may combine it with information that does identify you.</li>
                <li style="margin-bottom: 0.5rem; color: #444;">Information Collected by Cookies and Other Technologies. We use “cookies” and other technologies to collect information and support certain features of the Sites.</li>
            </ul>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">o Cookies: (a) collect data about the way you interact with our Site (e.g., when you use certain features or upload attachments), (b) collect data to assess and improve our advertising campaigns, (c) allow our business partners (including third parties) to use these tracking technologies to track your behavior on our behalf on our Site (including when you use multiple devices) and on partner websites, (d) enable third parties to collect data about the way you interact across sites outside of our Site, and (e) collect anonymous statistical information about how you use the Sites (including the length of your web or application session) and the location from which you access the Sites, so that we can improve the Sites and our services and learn which elements and functions of this Site are most popular with our users. You can manage your cookie’s data through your web browser’s settings.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">o Web beacons or pixels: These are tiny graphics with a unique identifier that are used to understand browsing activity. In contrast to cookies, these are rendered invisibly on web pages when you open a page.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">o Social widgets: These are buttons or icons provided by third-party social media providers that allow you to interact with their social media services when you view a web page or a mobile app screen. These social widgets may collect browsing data, which may be received by the third party that provided the widget and are controlled by the third parties.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">o UTM Source codes: These are strings that can appear in a URL (the “Uniform Resource Locator,” which is typically the http or https address entered to go to a web page) when a user moves from one web page or website to another, where the string can represent information about browsing, such as which advertisement, page, or publisher sent the user to the receiving website.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Keep in mind, we do not sell, license, or otherwise disclose your personal information to third parties for their marketing purposes without your consent.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">The majority of browsers accept Cookies automatically. If you want to change this browser setting, you can configure your browser so that no Cookies are stored on your device or a message is always displayed before a new Cookie is created. A general objection to the use of cookies used for online marketing purposes can be made for a variety of services, e.g. at http://www.youronlinechoices.com/ or the deactivation page of the Network Advertising Initiative http://optout.networkadvertising.org. However, disabling Cookies may affect the usability of our website.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Your Rights</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">We respect your right under applicable data protection law and regulations (including, if you are located within the European Economic Area, the General Data Protection Regulation (EU) 2016/679) to access, correct, and/or request limitations on our use, or the deletion, of all or any portion of your personal information and data collected. We also take steps to ensure that the personal information we collect is accurate, up to date and in accordance with our Data Protection Policy, as set forth herein. After verification of identity you have the right to:</p>
            <ul style="margin-bottom: 1.5rem; padding-left: 20px;">
                <li style="margin-bottom: 0.5rem; color: #444;">know what personal information and data we maintain about you (right of confirmation)</li>
                <li style="margin-bottom: 0.5rem; color: #444;">request a copy of your personal information in a structured, commonly used and machine-readable format (right to data portability)</li>
                <li style="margin-bottom: 0.5rem; color: #444;">request updates to or rectifications of your personal information if it is incorrect or incomplete</li>
                <li style="margin-bottom: 0.5rem; color: #444;">request that we cease our processing of your personal information and data</li>
                <li style="margin-bottom: 0.5rem; color: #444;">request us to delete (right to be forgotten) or restrict how we use your personal information, but this right is determined by applicable law and may impact your access to some of the services available on or through the Sites</li>
                <li style="margin-bottom: 0.5rem; color: #444;">object to our processing of your personal information</li>
                <li style="margin-bottom: 0.5rem; color: #444;">withdraw your consent to the processing of your personal information</li>
            </ul>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">In order to exercise any of these rights, please contact the Data Protection officer listed in this Policy.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">California Users: “Do Not Track” Disclosures</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">California law requires us to let you know how we respond to web browser Do Not Track (DNT) signals. DNT is a privacy preference that users can set in their web browsers as a way to inform websites and services that the users do not want certain information about their webpage visits collected over time and across websites or online services. Because there is no consensus or common understanding on how to interpret DNT or similar signals, we do not currently respond to DNT signals. We will adhere to this policy, subject to reconsideration if and when there is a common understanding of how to treat DNT and similar signals.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Third-Party Cookies</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">In addition to the cookie we deliver to your computer or mobile device through the Sites, certain third parties may deliver cookies to you for a variety of reasons. For example, we use Google Analytics, a web analytics tool that helps us understand how visitors engage with our Sites.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Google Analytics tracks traffic to our website and tracks and monitors the use of our services. This data is shared with other Google services and may be used by Google to contextualize and personalize the ads of its own advertising network. You can opt out of having your activity on our website available to Google Analytics by installing the Google Analytics opt-out browser add-on. For more information regarding the privacy practices and policies of Google, you can visit the Google Privacy &amp; Terms webpage: https://policies.google.com/privacy?hl=en.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Other third parties may deliver cookies to your computer or mobile device for the purpose of tracking your online behavior over time and across nonaffiliated websites and/or delivering targeted advertisements either on the Sites or on other websites. You can opt out of our use of cookies and similar technologies that track your behavior on the sites of others for third-party advertising.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Google has entered the EU/ US PrivacyShield, and is thereby committed to comply with European privacy standards and therefore is in compliance with the requirements of the European Union to legitimize the transfer of personal data to the United States. Information on Google’s commitment concerning the PrivacyShield can be found under:</p>
            <ul style="margin-bottom: 1.5rem; padding-left: 20px;">
                <li style="margin-bottom: 0.5rem; color: #444;">https://www.privacyshield.gov/participant?id=a2zt000000001L5AAI&amp;status=Active.</li>
            </ul>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">For more information about how Google handles your personal data, please see the privacy policy of Google: https://www.google.com/intl/en/policies/privacy/.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Information about the use of data for advertising purposes by Google, setting and contradictory options, you can found on these websites:</p>
            <ul style="margin-bottom: 1.5rem; padding-left: 20px;">
                <li style="margin-bottom: 0.5rem; color: #444;">https://policies.google.com/technologies/partner-sites?hl=en</li>
                <li style="margin-bottom: 0.5rem; color: #444;">https://policies.google.com/technologies/ads?hl=en</li>
                <li style="margin-bottom: 0.5rem; color: #444;">https://adssettings.google.com/authenticated</li>
                <li style="margin-bottom: 0.5rem; color: #444;">http://www.google.com/ads/preferences/</li>
            </ul>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Demographic Characteristics by Google Analytics</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">The Sites use the function “demographic characteristics” as part of Google Analytics. Thereby reports can be created that contain information on the age, gender and interest of our Sites’ visitors. This data comes from interest-based advertising from Google and third-party visitor data. This data cannot be assigned to a specific person. Legal basis for the use of the following services of Google are our legitimate interests to optimize and optimally market our Sites.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">You can disable this feature at any time through the display settings in your Google account or generally prohibit the collection of your data by Google Analytics as outlined above.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Google Maps</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">The Sites use Google Maps by Google to display site plans, maps, terrain data or geographic maps. This service collects your IP address, which of our Sites you have visited and, if applicable, other data required by Google for the provision of Maps (e.g. location data). Generated information will be stored on a server in the USA. This information will be transferred to third parties if required by law or if third parties process these data on behalf of us or Google. The terms of use for Google Maps can be found at: https://developers.google.com/maps/terms-20180207</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Google Tag Manager</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">The Sites use Google Tag Manager for tagging. This service allows website tags to be managed by a single interface. The Google Tag Manager only implements tags. That means: No cookies are used and no personal data is collected. The Google Tag Manager triggers other tags which may collect data. However, Google Tag Manager does not access this data. If there was a deactivation at the domain or cookie level it will remain in effect for all tracking tags as far as they it is implemented with the Google Tag Manager.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Google Ads</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">The Sites use Google Ads. Google Ads is an online advertising platform developed by Google, where advertisers pay to display brief advertisements, service offerings, product listings, video content and generate mobile application installs within the Google ad network to web users. Google Ads’ system is based partly on cookies and partly on keywords determined by advertisers. Google uses these characteristics to place advertising copy on pages where they think it might be relevant. Advertisers pay when users divert their browsing to click on the advertising copy. Partner websites receive a portion of the generated income. All ads on AdWords are eligible to be shown on Google’s search engine. Advertisers also have the option of enabling their ads to show on Google’s partner networks. This “search network” includes AOL search, Ask.com, and Netscape. The terms of use for Google Ads can be found at: https://support.google.com/google-ads/answer/7501778?hl=en</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Google Adsense</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">The Sites use Google Adsense. Google AdSense is a program run by Google that allows publishers in the Google Network of content sites to serve automatic text, image, video, or interactive media advertisements, that are targeted to site content and audience. These advertisements are administered, sorted, and maintained by Google. They can generate revenue on either a per-click or per-impression basis. The terms of use for Google AdSense can be found at: https://www.google.com/adsense/terms</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Data Protection Policy</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">We take a number of steps to protect your data, but no security is guaranteed.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">We take precautions to protect your information, including appropriate technical and organizational measures to protect your personal information from unauthorized disclosure or access. When you submit sensitive information via the Site, your information is protected both online and offline. Wherever we collect sensitive information, that information is encrypted and transmitted to us by secure servers. We have included common indications of such secured features when appropriate such as a closed lock icon in your web browser. While we use encryption to protect sensitive information transmitted online, we also protect your information offline. Only employees who need the information to perform a specific job (for example, billing or customer service) are granted access to personally identifiable information. The computers/servers in which we store personally identifiable information are kept in a secure environment.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Opting Out of Communications</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">If you do not wish to receive marketing communications from us, you can unsubscribe via the link in an email you have received.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Children’s Privacy</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">You must be at least 13 years old to have our permission to use the Sites. We do not knowingly collect, use or disclose personal information about visitors under 13 years of age. If you are under the age of 13, please do not use the Sites.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Testimonials</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">The Site may display personal testimonials of yours from time to time received via email or as otherwise received from you by the Site. If you would like the Site to remove your testimonial or customer review at any time, please simply contact us at the information included within this Policy and we will promptly do so.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Payment Service Provider</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">In connection with and for the purpose of fulfilling pre-contractual measures and contractual obligations via our website upon request of the data subject, we process the data of the data subject required for the fulfillment of the contract. This includes:</p>
            <ul style="margin-bottom: 1.5rem; padding-left: 20px;">
                <li style="margin-bottom: 0.5rem; color: #444;">Data of the contractor, such as name, address, phone number and contact details, if applicable different delivery or billing addresses or recipients, roommate request and gender;</li>
                <li style="margin-bottom: 0.5rem; color: #444;">Contractual data, such as subject of the contract, duration, customer category;</li>
                <li style="margin-bottom: 0.5rem; color: #444;">Payment data, such as bank details, credit card data, payment history.</li>
            </ul>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">The data will be transferred to third parties to fulfil pre-contractual and contractual obligations, e.g. to banks, payment service providers and credit card companies for the payment transaction and to e-mail service providers.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Surveys &amp; Contests</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">From time to time our site requests information via surveys or contests. Participation in these surveys or contests is completely voluntary and you may choose whether or not to participate and therefore whether or not to disclose information sought by such surveys or contests. Information requested may include contact information (such as name and shipping address), and demographic information (such as zip code, age level). Contact information will be used to notify the winners and award prizes. Survey information will be used for purposes of monitoring or improving the use and satisfaction of this Site.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Updates and Changes to Privacy Policy</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">We reserve the right, at any time and without notice, to add to, change, update or modify this Privacy Policy, by posting such change, update or modification on the Site. Any such change, update or modification will be effective immediately upon posting.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Governing Law</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">This Policy shall be governed under the laws of the Province of Ontario, Canada, without regard to its conflicts of law provisions.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Data Protection Inquiries</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">If you have any questions or concerns regarding our notice or if you believe our notice or applicable laws relating to the protection of your personal information have not been respected, you can file a complaint with our Data Protection Officer listed below and we will respond to let you know who will be handling your matter and when you can expect a further response. We may request additional details from you regarding your concerns and may need to engage or consult with other parties in order to investigate and address your issue(s). Records will be kept of any requests.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Please contact our Front Desk with any questions or concerns regarding this Privacy Notice.</p>
            <p style="margin-top: 2rem; color: #444;">107 Princes' Boulevard,<br>M6K 3C3,<br>Toronto</p>
        </div>
    </section>

<?php get_footer(); ?>
