<?php
/**
 * Template Name: Terms & Conditions
 */
get_header(); ?>

    <section class="page-hero" style="background: linear-gradient(135deg, rgba(0, 0, 0, 0.8) 0%, rgba(0, 0, 0, 0.6) 100%); height: 30vh; min-height: 250px;">
        <div class="container">
            <h1>Terms & Conditions</h1>
        </div>
    </section>

    <section class="legal-content" style="padding: 4rem 0; background-color: #fff;">
        <div class="container" style="max-width: 800px; margin: 0 auto; padding: 0 20px;">
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">These terms of use are entered into by and between You and Princes Gate Hotel LP, Inc. (”Company”, “we” or “us”). The following terms and conditions, together with any documents they expressly incorporate by reference (collectively, these “Terms of Use”), govern Your access to and use of this Library Hotel Collection (“LHC”) web site (“Site”) and the web sites (“Sites”) of affiliated hotels, including any content, functionality, and services offered on or through the Sites (the “Sites”), whether as a guest or a registered user.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Please read the Terms of Use carefully before You start to use the Sites. By using the Sites or by clicking to accept or agree to the Terms of Use when this option is made available to You, You accept and agree to be bound and abide by these Terms of Use and our Privacy Policy, found at https://tenxtoronto.com/en/privacy-policy.html, incorporated herein by reference. If You do not want to agree to these Terms of Use or the Privacy Policy, You must not access or use the Sites.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">​</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">The Sites are offered and available to users who are 21 years of age or older. By using the Sites, You represent and warrant that You are of legal age to form a binding contract with the Company and meet all of the foregoing eligibility requirements. If You do not meet all of these requirements, You must not access or use the Sites.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Changes to the Terms of Use</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">We may revise and update these Terms of Use from time to time in our sole discretion. All changes are effective immediately when we post them, and apply to all access to and use of the Sites thereafter. However, any changes to the dispute resolution provisions set out in Governing Law and Jurisdiction will not apply to any disputes for which the parties have actual notice before the date the change is posted on the Sites.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Your continued use of the Sites following the posting of revised Terms of Use means that You accept and agree to the changes. You are expected to check this page from time to time so You are aware of any changes, as they are binding on You.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Accessing the Sites and Account Security</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">We reserve the right to withdraw or amend the Sites, and any service or material we provide on the Sites, in our sole discretion without notice. We will not be liable if for any reason all or any part of the Sites is unavailable at any time or for any period. From time to time, we may restrict access to some parts of the Sites, or the entire Sites, to users, including registered users.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">You are responsible for:</h3>
            <ul style="margin-bottom: 1.5rem; padding-left: 20px;">
                <li style="margin-bottom: 0.5rem; color: #444;"></li>
            </ul>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Making all arrangements necessary for You to have access to the Sites.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Ensuring that all persons who access the Sites through Your Internet connection are aware of these Terms of Use and comply with them.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Making all arrangements necessary for You to have access to the Sites.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Ensuring that all persons who access the Sites through Your Internet connection are aware of these Terms of Use and comply with them.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">To access the Sites or some of the resources they offer, You may be asked to provide certain registration details or other information. It is a condition of Your use of the Sites that all the information You provide on the Sites is correct, current, and complete. You agree that all information You provide to register with the Sites or otherwise, including but not limited to the use of any interactive features on the Sites, is governed by our Privacy Policy, found at https://tenxtoronto/en/privacy-policy.html, and You consent to all actions we take with respect to Your information consistent with our Privacy Policy.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">If You choose, or are provided with, a user name, password, or any other piece of information as part of our security procedures, You must treat such information as confidential, and You must not disclose it to any other person or entity. You also acknowledge that Your account is personal to You and agree not to provide any other person with access to the Sites or portions of it using Your user name, password, or other security information. You agree to notify us immediately of any unauthorized access to or use of Your user name or password or any other breach of security. You also agree to ensure that You exit from Your account at the end of each session. You should use particular caution when accessing Your account from a public or shared computer so that others are not able to view or record Your password or other personal information.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">We have the right to disable any user name, password, or other identifier, whether chosen by You or provided by us, at any time in our sole discretion for any or no reason, including if, in our opinion, You have violated any provision of these Terms of Use.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Intellectual Property Rights</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">The Sites and their entire contents, features, and functionality (including but not limited to all information, software, text, displays, images, video, and audio, and the design, selection, and arrangement thereof), are owned by the Company, its licensors, or other providers of such material and are protected by United States and international copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">These Terms of Use permit You to use the Sites for Your personal, non-commercial use only. You must not reproduce, distribute, modify, create derivative works of, publicly display, publicly perform, republish, download, store, or transmit any of the material on our Sites, except as follows:</p>
            <ul style="margin-bottom: 1.5rem; padding-left: 20px;">
                <li style="margin-bottom: 0.5rem; color: #444;"></li>
            </ul>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Your computer may temporarily store copies of such materials in RAM incidental to Your accessing and viewing those materials.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">You may store files that are automatically cached by Your Web browser for display enhancement purposes.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">You may print or download one copy of a reasonable number of pages of the Sites for Your own personal, non-commercial use and not for further reproduction, publication, or distribution.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">If we provide desktop, mobile, or other applications for download, You may download a single copy to Your computer or mobile device solely for Your own personal, non-commercial use, provided You agree to be bound by our end user license agreement for such applications.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">If we provide social media features with certain content, You may take such actions as are enabled by such features.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Your computer may temporarily store copies of such materials in RAM incidental to Your accessing and viewing those materials.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">You may store files that are automatically cached by Your Web browser for display enhancement purposes.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">You may print or download one copy of a reasonable number of pages of the Sites for Your own personal, non-commercial use and not for further reproduction, publication, or distribution.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">If we provide desktop, mobile, or other applications for download, You may download a single copy to Your computer or mobile device solely for Your own personal, non-commercial use, provided You agree to be bound by our end user license agreement for such applications.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">If we provide social media features with certain content, You may take such actions as are enabled by such features.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">You must not:</h3>
            <ul style="margin-bottom: 1.5rem; padding-left: 20px;">
                <li style="margin-bottom: 0.5rem; color: #444;"></li>
            </ul>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Modify copies of any materials from this site.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Use any illustrations, photographs, video or audio sequences, or any graphics separately from the accompanying text.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Delete or alter any copyright, trademark, or other proprietary rights notices from copies of materials from this site.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Modify copies of any materials from this site.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Use any illustrations, photographs, video or audio sequences, or any graphics separately from the accompanying text.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Delete or alter any copyright, trademark, or other proprietary rights notices from copies of materials from this site.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">You must not access or use for any commercial purposes any part of the Sites or any services or materials available through the Sites.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">If You wish to make any use of material on the Sites other than that set out in this section, please address Your request to: service@libraryhotelcollection.com</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">If You print, copy, modify, download, or otherwise use or provide any other person with access to any part of the Sites in breach of the Terms of Use, Your right to use the Sites will stop immediately and You must, at our option, return or destroy any copies of the materials You have made. No right, title, or interest in or to the Sites or any content on the Sites is transferred to You, and all rights not expressly granted are reserved by the Company. Any use of the Sites not expressly permitted by these Terms of Use is a breach of these Terms of Use and may violate copyright, trademark, and other laws.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Trademarks</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">The Company name, the terms LIBRARY HOTEL COLLECTION, HOTEL X, ARIA, LIBRARY HOTEL, HOTEL GIRAFFE, CASABLANCA HOTEL and HOTEL ELYSEE, and all related names, logos, product and service names, designs, and slogans are trademarks of the Company or its affiliates or licensors. You must not use such marks without the prior written permission of the Company. All other names, logos, product and service names, designs, and slogans on the Sites are the trademarks of their respective owners.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Prohibited Uses</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">You may use the Sites only for lawful purposes and in accordance with these Terms of Use. You agree not to use the Sites:</p>
            <ul style="margin-bottom: 1.5rem; padding-left: 20px;">
                <li style="margin-bottom: 0.5rem; color: #444;"></li>
            </ul>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">In any way that violates any applicable federal, state, local, or international law or regulation (including, without limitation, any laws regarding the export of data or software to and from the US or other countries).</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">For the purpose of exploiting, harming, or attempting to exploit or harm minors in any way by exposing them to inappropriate content, asking for personally identifiable information, or otherwise.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">To transmit, or procure the sending of, any advertising or promotional material, including any “junk mail”, “chain letter”, “spam”, or any other similar solicitation.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">To impersonate or attempt to impersonate the Company, a Company employee, another user, or any other person or entity (including, without limitation, by using email addresses or screen names associated with any of the foregoing).</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">To engage in any other conduct that restricts or inhibits anyone’s use or enjoyment of the Sites, or which, as determined by us, may harm the Company or users of the Sites or expose them to liability.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">In any way that violates any applicable federal, state, local, or international law or regulation (including, without limitation, any laws regarding the export of data or software to and from the US or other countries).</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">For the purpose of exploiting, harming, or attempting to exploit or harm minors in any way by exposing them to inappropriate content, asking for personally identifiable information, or otherwise.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">To transmit, or procure the sending of, any advertising or promotional material, including any “junk mail”, “chain letter”, “spam”, or any other similar solicitation.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">To impersonate or attempt to impersonate the Company, a Company employee, another user, or any other person or entity (including, without limitation, by using email addresses or screen names associated with any of the foregoing).</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">To engage in any other conduct that restricts or inhibits anyone’s use or enjoyment of the Sites, or which, as determined by us, may harm the Company or users of the Sites or expose them to liability.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Additionally, You agree not to:</h3>
            <ul style="margin-bottom: 1.5rem; padding-left: 20px;">
                <li style="margin-bottom: 0.5rem; color: #444;"></li>
            </ul>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Use the Sites in any manner that could disable, overburden, damage, or impair the site or interfere with any other party’s use of the Sites, including their ability to engage in real time activities through the Sites.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Use any robot, spider, or other automatic device, process, or means to access the Sites for any purpose, including monitoring or copying any of the material on the Sites.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Use any manual process to monitor or copy any of the material on the Sites or for any other unauthorized purpose without our prior written consent.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Use any device, software, or routine that interferes with the proper working of the Sites.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Introduce any viruses, trojan horses, worms, logic bombs, or other material that is malicious or technologically harmful.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Attempt to gain unauthorized access to, interfere with, damage, or disrupt any parts of the Sites, the server on which the Sites is stored, or any server, computer, or database connected to the Sites.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Attack the Sites via a denial-of-service attack or a distributed denial-of-service attack.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Otherwise attempt to interfere with the proper working of the Sites.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Use the Sites in any manner that could disable, overburden, damage, or impair the site or interfere with any other party’s use of the Sites, including their ability to engage in real time activities through the Sites.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Use any robot, spider, or other automatic device, process, or means to access the Sites for any purpose, including monitoring or copying any of the material on the Sites.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Use any manual process to monitor or copy any of the material on the Sites or for any other unauthorized purpose without our prior written consent.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Use any device, software, or routine that interferes with the proper working of the Sites.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Introduce any viruses, trojan horses, worms, logic bombs, or other material that is malicious or technologically harmful.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Attempt to gain unauthorized access to, interfere with, damage, or disrupt any parts of the Sites, the server on which the Sites is stored, or any server, computer, or database connected to the Sites.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Attack the Sites via a denial-of-service attack or a distributed denial-of-service attack.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Otherwise attempt to interfere with the proper working of the Sites.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Reliance on Information Posted</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">The information presented on or through the Sites is made available solely for general information purposes. We do not warrant the accuracy, completeness, or usefulness of this information. Any reliance You place on such information is strictly at Your own risk. We disclaim all liability and responsibility arising from any reliance placed on such materials by You or any other visitor to the Sites, or by anyone who may be informed of any of its contents.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">The Sites may include content provided by third parties, including materials provided by other users, bloggers, and third-party licensors, syndicators, aggregators, and/or reporting services. All statements and/or opinions expressed in these materials, and all articles and responses to questions and other content, other than the content provided by the Company, are solely the opinions and the responsibility of the person or entity providing those materials. These materials do not necessarily reflect the opinion of the Company. We are not responsible, or liable to You or any third party, for the content or accuracy of any materials provided by any third parties.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Changes to the Sites</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">We may update the content on the Sites from time to time, but their content is not necessarily complete or up-to-date. Any of the material on the Sites may be out of date at any given time, and we are under no obligation to update such material.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Information About You and Your Visits to the Sites.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">All information we collect on the Sites is subject to our Privacy Policy found at https://tenxtoronto.com/en/privacy-policy.html. By using the Sites, You consent to all actions taken by us with respect to Your information in compliance with the Privacy Policy.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Linking to the Sites and Social Media Features</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">You may link to our homepage, provided You do so in a way that is fair and legal and does not damage our reputation or take advantage of it, but You must not establish a link in such a way as to suggest any form of association, approval, or endorsement on our part.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">This Sites may provide certain social media features that enable You to:</p>
            <ul style="margin-bottom: 1.5rem; padding-left: 20px;">
                <li style="margin-bottom: 0.5rem; color: #444;"></li>
            </ul>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Link from Your own or certain third-party web sites to certain content on the Sites.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Send emails or other communications with certain content, or links to certain content, on the Sites.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Cause limited portions of content on the Sites to be displayed or appear to be displayed on Your own or certain third-party web sites.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Link from Your own or certain third-party web sites to certain content on the Sites.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Send emails or other communications with certain content, or links to certain content, on the Sites.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Cause limited portions of content on the Sites to be displayed or appear to be displayed on Your own or certain third-party web sites.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">You may use these features solely as they are provided by us, and solely with respect to the content they are displayed with and otherwise in accordance with any additional terms and conditions we provide with respect to such features. Subject to the foregoing, You must not:</p>
            <ul style="margin-bottom: 1.5rem; padding-left: 20px;">
                <li style="margin-bottom: 0.5rem; color: #444;"></li>
            </ul>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Establish a link from any web site that is not owned by You.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Cause the Sites or portions of it to be displayed on, or appear to be displayed by, any other site, for example, framing, deep linking, or in-line linking.</p>
            <ul style="margin-bottom: 1.5rem; padding-left: 20px;">
                <li style="margin-bottom: 0.5rem; color: #444;"></li>
            </ul>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Link to any part of the Sites other than the homepage.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Otherwise take any action with respect to the materials on the Sites that is inconsistent with any other provision of these Terms of Use.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Establish a link from any web site that is not owned by You.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Cause the Sites or portions of it to be displayed on, or appear to be displayed by, any other site, for example, framing, deep linking, or in-line linking.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Link to any part of the Sites other than the homepage.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Otherwise take any action with respect to the materials on the Sites that is inconsistent with any other provision of these Terms of Use.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">You agree to cooperate with us in causing any unauthorized framing or linking immediately to stop. We reserve the right to withdraw linking permission without notice.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">We may disable all or any social media features and any links at any time without notice in our discretion.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Links from the Sites</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">If the Sites contain links to other sites and resources provided by third parties, these links are provided for Your convenience only. This includes links contained in advertisements, including banner advertisements and sponsored links. We have no control over the contents of those sites or resources, and accept no responsibility for them or for any loss or damage that may arise from Your use of them. If You decide to access any of the third-party web sites linked to the Sites, You do so entirely at Your own risk and subject to the terms and conditions of use for such web sites.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Disclaimer of Warranties</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">You understand that we cannot and do not guarantee or warrant that files available for downloading from the Internet or the Sites will be free of viruses or other destructive code. You are responsible for implementing sufficient procedures and checkpoints to satisfy Your particular requirements for anti-virus protection and accuracy of data input and output, and for maintaining a means external to our site for any reconstruction of any lost data. TO THE FULLEST EXTENT PROVIDED BY LAW, WE WILL NOT BE LIABLE FOR ANY LOSS OR DAMAGE CAUSED BY A DISTRIBUTED DENIAL-OF-SERVICE ATTACK, VIRUSES, OR OTHER TECHNOLOGICALLY HARMFUL MATERIAL THAT MAY INFECT YOUR COMPUTER EQUIPMENT, COMPUTER PROGRAMS, DATA, OR OTHER PROPRIETARY MATERIAL DUE TO YOUR USE OF THE WEB SITES OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE WEB SITES OR TO YOUR DOWNLOADING OF ANY MATERIAL POSTED ON THEM, OR ON ANY WEB SITE LINKED TO THEM.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">YOUR USE OF THE WEB SITES, THEIR CONTENT, AND ANY SERVICES OR ITEMS OBTAINED THROUGH THE WEB SITES IS AT YOUR OWN RISK. THE WEB SITES, THEIR CONTENT, AND ANY SERVICES OR ITEMS OBTAINED THROUGH THE WEB SITES ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS, WITHOUT ANY WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. NEITHER THE COMPANY NOR ANY PERSON ASSOCIATED WITH THE COMPANY MAKES ANY WARRANTY OR REPRESENTATION WITH RESPECT TO THE COMPLETENESS, SECURITY, RELIABILITY, QUALITY, ACCURACY, OR AVAILABILITY OF THE WEB SITES. WITHOUT LIMITING THE FOREGOING, NEITHER THE COMPANY NOR ANYONE ASSOCIATED WITH THE COMPANY REPRESENTS OR WARRANTS THAT THE WEB SITES, THEIR CONTENT, OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE WEB SITES WILL BE ACCURATE, RELIABLE, ERROR-FREE, OR UNINTERRUPTED, THAT DEFECTS WILL BE CORRECTED, THAT OUR SITE OR THE SERVER THAT MAKES THEM AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS, OR THAT THE WEB SITES OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE WEB SITES WILL OTHERWISE MEET YOUR NEEDS OR EXPECTATIONS.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">TO THE FULLEST EXTENT PROVIDED BY LAW, THE COMPANY HEREBY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT, AND FITNESS FOR PARTICULAR PURPOSE.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">THE FOREGOING DOES NOT AFFECT ANY WARRANTIES THAT CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Limitation on Liability</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">TO THE FULLEST EXTENT PROVIDED BY LAW, IN NO EVENT WILL THE COMPANY, ITS AFFILIATES, OR THEIR LICENSORS, SERVICE PROVIDERS, EMPLOYEES, AGENTS, OFFICERS, OR DIRECTORS BE LIABLE FOR DAMAGES OF ANY KIND, UNDER ANY LEGAL THEORY, ARISING OUT OF OR IN CONNECTION WITH YOUR USE, OR INABILITY TO USE, THE WEB SITES, ANY WEB SITES LINKED TO THEM, ANY CONTENT ON THE WEB SITES OR SUCH OTHER WEB SITES, INCLUDING ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO, PERSONAL INJURY, PAIN AND SUFFERING, EMOTIONAL DISTRESS, LOSS OF REVENUE, LOSS OF PROFITS, LOSS OF BUSINESS OR ANTICIPATED SAVINGS, LOSS OF USE, LOSS OF GOODWILL, LOSS OF DATA, AND WHETHER CAUSED BY TORT (INCLUDING NEGLIGENCE), BREACH OF CONTRACT, OR OTHERWISE, EVEN IF FORESEEABLE.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">THE FOREGOING DOES NOT AFFECT ANY LIABILITY THAT CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Indemnification</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">You agree to defend, indemnify, and hold harmless the Company, its affiliates, licensors, and service providers, and its and their respective officers, directors, employees, contractors, agents, licensors, suppliers, successors, and assigns from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees (including reasonable attorneys’ fees) arising out of or relating to Your violation of these Terms of Use or Your use of the Sites, including, but not limited to, Your User Contributions, any use of the Sites’s content, services, and products other than as expressly authorized in these Terms of Use or Your use of any information obtained from the Sites.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Governing Law and Jurisdiction</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">All matters relating to the Sites and these Terms of Use and any dispute or claim arising therefrom or related thereto (in each case, including non-contractual disputes or claims), shall be governed by and construed in accordance with the internal laws of the State of New York without giving effect to any choice or conflict of law provision or rule (whether of the State of New York or any other jurisdiction).</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Any legal suit, action, or proceeding arising out of, or related to, these Terms of Use or the Sites shall be instituted exclusively in the federal courts of the United States or the courts of the State of New York in each case located in the City of New York and County of New York although we retain the right to bring any suit, action, or proceeding against You for breach of these Terms of Use in Your state or country of residence or any other relevant state or country. You waive any and all objections to the exercise of jurisdiction over You by such courts and to venue in such courts.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Arbitration</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">At Company’s sole discretion, it may require You to submit any disputes arising from the use of these Terms of Use or the Sites, including disputes arising from or concerning their interpretation, violation, invalidity, non-performance, or termination, to final and binding arbitration under the Rules of Arbitration of the American Arbitration Association applying New York law.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Waiver and Severability</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">No perceived or specific waiver by the Company of any term or condition set out in these Terms of Use shall be deemed a further or continuing waiver of such term or condition or a waiver of any other term or condition, and any failure of the Company to assert a right or provision under these Terms of Use shall not constitute a waiver of such right or provision.</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">If any provision of these Terms of Use is held by a court or other tribunal of competent jurisdiction to be invalid, illegal or unenforceable for any reason, such provision shall be eliminated or limited to the minimum extent such that the remaining provisions of the Terms of Use will continue in full force and effect.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Entire Agreement</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">The Terms of Use and our Privacy Policy constitute the sole and entire agreement between You and Princes Gates Hotel LP, Inc. regarding the Sites and supersede all prior and contemporaneous understandings, agreements, representations, and warranties, both written and oral, regarding the Sites.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Your Comments and Concerns</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Feedback, comments, requests for technical support, and other communications relating to the Sites should be directed to: service@libraryhotelcollection.co</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">URL: 10XTO.com</h3>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Company, organization: Ten X Toronto Athletic Club</h3>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Registered Offices:</h3>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Ten X Toronto</h3>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">107 Princes’ Boulevard</h3>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Toronto M6K 3C3 - CANADA</h3>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Tel: +1 647.475.9296</h3>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">info@tenxtoronto.com</h3>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Share capital:</h3>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">VAT number:</h3>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Purpose of site: Promotion of the establishment</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Director of publication, legal representative: Mrs Adele GUTMAN</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Editorial Manager: Mrs Adele GUTMAN</h3>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Webmaster, design, editing, artistic direction: SAS WIHP</h3>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Photography: SAS WIHP</h3>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Web hosting: SAS WIHP</h3>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">President SAS WIHP: Vincent Ramelli</h3>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">The site presents:</h3>
            <ul style="margin-bottom: 1.5rem; padding-left: 20px;">
                <li style="margin-bottom: 0.5rem; color: #444;"></li>
            </ul>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Informative content</h3>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">A collection of personal data on line</h3>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">Informative content</h3>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">A collection of personal data on line</h3>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">French Data Protection Act: the site is the subject of a declaration to the Commission Nationale Informatique and Liberté (French Data Protection Authority). You have the right to access, modify, rectify and delete information that concerns you (art. 34 of the Loi Informatique et Libertés (French Data Protection Act)). To exercise this right, please contact: info@tenxtoronto.com</p>
            <p style="margin-bottom: 1.5rem; line-height: 1.8; color: #444;">Ownership: The site and the information that it contains are protected by French intellectual property law and by international agreements. Except for use by immediate family members or private use, the site and any element of its content may not be reproduced, republished, retranscribed, modified or passed on without the prior authorization of the eligible party.</p>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">​</h3>
            <h3 style="margin-top: 2.5rem; margin-bottom: 1rem; color: #111; font-weight: 600;">​</h3>
        </div>
    </section>

<?php get_footer(); ?>
