name: Deploy Theme to WHC

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  web-deploy:
    name: Deploy to WHC
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Remove hidden files to prevent server blocks
      run: rm -rf .git .github

    - name: Deploy to WHC via SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SFTP_SERVER }}
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        port: ${{ secrets.SFTP_PORT }}
        source: "./"
        target: "./public_html/wp-content/themes/10xto-wordpress-theme/"
        overwrite: true
