name: Deploy Theme to WHC

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy to WHC
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: LFTP Force Mirror
      run: |
        sudo apt-get update && sudo apt-get install lftp -y
        lftp -c "set sftp:auto-confirm yes;
        open -u ${{ secrets.SFTP_USERNAME }},${{ secrets.SFTP_PASSWORD }} sftp://${{ secrets.SFTP_SERVER }}:${{ secrets.SFTP_PORT }};
        mirror --reverse --verbose --overwrite --parallel=3 --exclude .git/ --exclude .github/ ./ ./public_html/wp-content/themes/10xto-wordpress-theme/"
